"""Constants for the Remote Devices integration."""

DOMAIN = "remote_devices"

CONF_EMITTER_ENTITY_ID = "emitter_entity_id"
CONF_DEVICE_TYPE = "device_type"
CONF_DEVICE_NAME = "device_name"
CONF_ATTACH_TO_DEVICE = "attach_to_device"

DEVICE_TYPE_NEC_TV = "nec_tv"
DEVICE_TYPE_SAMSUNG_TV = "samsung_tv"
DEVICE_TYPE_SHARP_TV = "sharp_tv"
DEVICE_TYPE_DENON_AVR = "denon_avr"
DEVICE_TYPE_AUDIOENGINE_A5 = "audioengine_a5"
DEVICE_TYPE_TRISTAR_AC = "tristar_ac"
DEVICE_TYPE_PHILIPS_LAMP = "philips_lamp"
DEVICE_TYPE_AMINO_STB = "amino_stb"
DEVICE_TYPE_RAW_TEST = "raw_test"
DEVICE_TYPE_AIRWIT_FAN = "airwit_fan"

DEVICE_TYPES = {
    DEVICE_TYPE_NEC_TV: "NEC TV (LG, most TVs)",
    DEVICE_TYPE_SAMSUNG_TV: "Samsung TV",
    DEVICE_TYPE_SHARP_TV: "Sharp TV (Aquos)",
    DEVICE_TYPE_DENON_AVR: "Denon AVR Receiver",
    DEVICE_TYPE_AUDIOENGINE_A5: "Audioengine A5+ Speakers",
    DEVICE_TYPE_TRISTAR_AC: "Tristar PD-8779 Air Conditioner (ZH/LT-01)",
    DEVICE_TYPE_PHILIPS_LAMP: "Philips RGBIC Lamp",
    DEVICE_TYPE_AMINO_STB: "Amino Kamai Set-top Box",
    DEVICE_TYPE_AIRWIT_FAN: "Airwit Plafondventilator (RF 433 MHz)",
    DEVICE_TYPE_RAW_TEST: "Raw Test Signal (just a burst)",
}

# Maps each device type to the transmitter protocol it uses ("ir" or "rf").
# Used by config_flow to filter emitters and by button.py / fan.py / light.py
# to dispatch to the right HA platform.
DEVICE_PROTOCOLS = {
    DEVICE_TYPE_NEC_TV: "ir",
    DEVICE_TYPE_SAMSUNG_TV: "ir",
    DEVICE_TYPE_SHARP_TV: "ir",
    DEVICE_TYPE_DENON_AVR: "ir",
    DEVICE_TYPE_AUDIOENGINE_A5: "ir",
    DEVICE_TYPE_TRISTAR_AC: "ir",
    DEVICE_TYPE_PHILIPS_LAMP: "ir",
    DEVICE_TYPE_AMINO_STB: "ir",
    DEVICE_TYPE_RAW_TEST: "ir",
    DEVICE_TYPE_AIRWIT_FAN: "rf",
}

# NEC Protocol
NEC_FREQUENCY_KHZ = 38
NEC_UNIT_US = 560
NEC_HEADER_MARK_US = 9000
NEC_HEADER_SPACE_US = 4500
NEC_ONE_MARK_US = NEC_UNIT_US
NEC_ONE_SPACE_US = 1690
NEC_ZERO_MARK_US = NEC_UNIT_US
NEC_ZERO_SPACE_US = NEC_UNIT_US
NEC_STOP_MARK_US = NEC_UNIT_US
NEC_STOP_SPACE_US = NEC_UNIT_US

# LG TV NEC codes (address 0x04)
LG_TV_ADDRESS = 0x04

LG_TV_COMMANDS = {
    "power": 0x08,
    "volume_up": 0x02,
    "volume_down": 0x03,
    "channel_up": 0x00,
    "channel_down": 0x01,
    "mute": 0x09,
    "input": 0x0B,
    "ok": 0x44,
    "up": 0x40,
    "down": 0x41,
    "left": 0x07,
    "right": 0x06,
    "back": 0x28,
    "home": 0xC4,
    "menu": 0x43,
    "play": 0xB0,
    "pause": 0xBA,
    "stop": 0xB1,
}

# Samsung TV NEC codes (address 0x07)
SAMSUNG_TV_ADDRESS = 0x07

SAMSUNG_TV_COMMANDS = {
    "power": 0x02,
    "volume_up": 0x07,
    "volume_down": 0x0B,
    "channel_up": 0x12,
    "channel_down": 0x10,
    "mute": 0x0F,
    "input": 0x01,
    "ok": 0x68,
    "up": 0x60,
    "down": 0x61,
    "left": 0x65,
    "right": 0x62,
    "back": 0x58,
    "home": 0x79,
    "menu": 0x1A,
}

# Sharp Protocol
SHARP_FREQUENCY_KHZ = 38
SHARP_BIT_MARK_US = 320
SHARP_ONE_SPACE_US = 1680
SHARP_ZERO_SPACE_US = 680
SHARP_FRAME_GAP_US = 40000  # 40ms gap between first and second (inverted) frame

# Denon Protocol (different timing from Sharp despite similar structure)
# IRP: {38k,264}<1,-3|1,-7>(D:5,F:8,0:2,1,-165,D:5,~F:8,3:2,1,-165)+
# No header pulse. Time unit = 264us.
DENON_FREQUENCY_KHZ = 38
DENON_BIT_MARK_US = 264  # 1 unit
DENON_ONE_SPACE_US = 1848  # 7 units (264 * 7)
DENON_ZERO_SPACE_US = 792  # 3 units (264 * 3)
DENON_FRAME_GAP_US = 43560  # 165 units (264 * 165)

# Sharp TV codes (address 1) — Sharp Aquos LC series
SHARP_TV_ADDRESS = 0x01

SHARP_TV_COMMANDS = {
    "power": 22,
    "volume_up": 20,
    "volume_down": 21,
    "channel_up": 17,
    "channel_down": 18,
    "mute": 23,
    "input": 19,
    "menu": 32,
    "display": 27,
    "flashback": 47,
    "0": 10,
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7": 7,
    "8": 8,
    "9": 9,
}

# Denon AVR codes (address 2) — Denon AV receivers
DENON_AVR_ADDRESS = 0x02

# Verified codes from actual Broadlink-learned AVR-2106 remote + IRDB.
DENON_AVR_COMMANDS = {
    "power_on": 225,
    "power_off": 226,
    "volume_up": 241,
    "volume_down": 242,
    "mute": 240,
    "input_cd": 66,
    "input_dvd": 227,
    "input_tv_dbs": 201,
    "input_tuner": 197,
    "input_vcr": 205,
    "input_v_aux": 204,
    "input_cdr_tape": 210,
    "pure_direct": 106,
    "stereo": 230,
    "standard": 228,
    "multi_channel": 219,
}

# Audioengine A5+ powered speakers — extended NEC protocol.
# 16-bit address 0x00FD (low byte 0x00, high byte 0xFD). Unlike standard NEC,
# the high byte is NOT the complement of the low byte, so it is specified
# explicitly via NECCommand(address_high=...).
# Codes verified against the Flipper Zero IR database and the JP1 Remotes forum.
AUDIOENGINE_A5_ADDRESS = 0x00
AUDIOENGINE_A5_ADDRESS_HIGH = 0xFD

# Power (0x01) is intentionally omitted: the A5+ powers on/off via the front
# volume knob, not the IR remote, so an IR power code has no effect.
AUDIOENGINE_A5_COMMANDS = {
    "volume_up": 0x09,
    "volume_down": 0x07,
    "mute": 0x03,
}

# Tristar PD-8779 portable air conditioner — ZH/LT-01 protocol.
# Stateful AC protocol: every press sends the full state in a 12-byte frame,
# LSB first, where each even byte is the bitwise complement of the next odd
# byte (the receiver's integrity check). Ported from the ESPHome `zhlt01`
# component and ToniA's HeatpumpIR ZHLT01. Carrier 38 kHz.
ZHLT01_FREQUENCY_KHZ = 38
ZHLT01_HDR_MARK_US = 6100
ZHLT01_HDR_SPACE_US = 7400
ZHLT01_BIT_MARK_US = 500
ZHLT01_ONE_SPACE_US = 1800
ZHLT01_ZERO_SPACE_US = 600

ZHLT01_REMOTE_ID = 0xD5  # byte 11

ZHLT01_TEMP_MIN = 16
ZHLT01_TEMP_MAX = 32

# Byte 7 fields: power | fan | vertical swing | horizontal swing
ZHLT01_POWER_OFF = 0x00
ZHLT01_POWER_ON = 0x02
ZHLT01_FAN_AUTO = 0x00
ZHLT01_FAN_SILENT = 0x01
ZHLT01_FAN_LOW = 0x60  # FAN1
ZHLT01_FAN_MEDIUM = 0x40  # FAN2
ZHLT01_FAN_HIGH = 0x20  # FAN3
ZHLT01_VDIR_SWING = 0x04
ZHLT01_VDIR_FIXED = 0x08
ZHLT01_HDIR_FIXED = 0x10

# Byte 9 fields: mode | (temperature - 16)
ZHLT01_MODE_AUTO = 0x00
ZHLT01_MODE_COOL = 0x20
ZHLT01_MODE_DRY = 0x40
ZHLT01_MODE_FAN = 0x60
ZHLT01_MODE_HEAT = 0x80

# Philips RGBIC Ambient Floor Lamp — NEC protocol (address 0x00)
PHILIPS_LAMP_ADDRESS = 0x00

PHILIPS_LAMP_COMMANDS = {
    "on": 0x03,
    "off": 0x02,
    "brightness_up": 0x00,
    "brightness_down": 0x01,
    "red": 0x04,
    "green": 0x05,
    "blue": 0x06,
    "white": 0x07,
    "orange": 0x08,
    "night_mode": 0x0B,
    "yellow": 0x0C,
}

# Amino Kamai 7X Set-top Box — RC6 protocol (raw Broadlink-learned codes).
# RC6 is too complex to encode from scratch, so we store the base64
# Broadlink packets and decode them to raw timings at runtime.
AMINO_STB_BROADLINK_CODES = {
    "power": "JgCEAFQdDRAODw0dDR4qHA4QDg4ODw0PDg8NDxseDg4ODw0PHQ4ODw0dDg4dHQ4PGw8OHQ4ODg8NDw4PHA8OHA4ODgAIs1UdDg8ODw0dDh0qHQ0QDRANDw4ODg8ODhwdDg8NDw4OHQ8NDw4cDg8cHQ4PGw8OHQ4PDQ8ODw0PHA8OHA4PDQANBQ==",
    "channel_up": "JgBCAFQdDRAODg4dDR4qHA4QDQ8ODw0PDg4ODxseDQ8ODw0PHA8ODw0PDh0cHQ4OHA8NHg0PDg8cHA4PDg8ODw0PDgANBQ==",
    "channel_down": "JgBaAFUcDhAMEA4cDh0qHQ4PDRANDw4PDQ8ODhwdDg8NDw4PHA8NDw4PDR4bHg0PGw8OHQ4PDQ8cHQ4ODg8ODh0ACLtVHA4QDBAOHA4dKxwODw0QDg4ODwwSCgANBQ==",
    "forward": "JgCAAFQdDg8NDw4dDhwqHg4ODg8NDw4PDQ8ODh0cDhANDw4PGw8NDw4dDg8cHA4PHA8OHA4QDQ8bHhseDQ8ODw0ACLNUHg4ODg8NHg4cKh4NDw4ODg8ODg4PDQ8cHQ4PDg8NDxwODg8NHg4OHRwODxwPDR0NEA4PGx0cHQ4PDQ8OAA0F",
    "rewind": "JgB8AFUdDRAODw0dDR4qHA4QDg4ODw0PDg8NDxseDg4ODw0PHQ4ODw0PDh0cHQ4PGw8NHg4ODg8cHRwcDhAbAAi8VRwODw0PDh0OHSscDg4ODw4PDRANDw4PGx0ODw4ODg8cDw4ODg8NHRweDQ8cDg4dDg8ODh0cHRwODxwADQU=",
    "play": "JgCAAFQcDg8ODw4cDh4qHA4QDBAODg4PDg4ODxseDQ8ODg4PHA8ODg4dDRAbHg0PHA4OHg0PDg4dHB0ODh0NEA4ACLJUHg4ODg8NHg4cKh4NDw4ODg8ODg4PDQ8dHQ4ODg8ODhwODhANHQ4OHRwODxwPDh0ODg4PGx4bEA0dDg4OAA0F",
    "pause": "JgCEAFQdDw4NDw4dDhwrHQ4ODg8ODg4PDQ8ODxwdDg8ODg4PGw8ODg4QDR0cHQ0PHA8OHQ4PDQ8cDg4dDg8ODg4PDgAIs1QeDQ8ODw0eDR0qHQ4PDg4ODw0PDg8NDxwdDg8NEA0PHA4ODw0PDh0dHA4PHA8NHQ4ODhAbDw4dDg4ODw4ODgANBQ==",
    "stop": "JgCAAFQeDg4ODw0eDhwqHg0PDg4ODw4ODg8NDx0cDg8ODw4OHA4ODw4dDg4dHA4PHA8OHA4PDg8bDw4dDg8NDxsACLxVHQ4ODg8OHQ4cKh4NDw4PDQ8ODw0PDg4dHA4QDBAODhwPDQ8OHQ4PHBwODxwPDhwOEAwQGw8OHQ4PDQ8cAA0F",
}

# Airwit Plafondventilator (ceiling fan with light) — RF 433 MHz, OOK modulation.
# Codes captured from the original Broadlink learn flow; same wire format as IR
# but the type byte is 0xb2 (RF 433) instead of 0x26 (IR).
AIRWIT_FAN_FREQUENCY_HZ = 433_920_000

AIRWIT_FAN_BROADLINK_RF_CODES = {
    # Light toggle (single button on the original remote)
    "lamp": "scBWArqeBgANIiQLJQwjDCQMDSMOIiMMDiMjDSMMDSQjDCMNIw0jDSINIw0jDQ0jIg0OIyINDSMjDSMMIw0kDCMNIg0NJCIPDaENJCMMIwwjDSQMDSMNIiQNDSMjDCQMDiIjDSQMIwwjDSQMIw0iDQ0kIwwOIiQMDiIjDCMOIwwjDCMOIg0NIyMODqANIyMMJA0jDCMNDSMNIyMMDSQjDCMNDSMjDSMMIw0jDSMMIw0jDQ0jIw0NIyMMDSMkDCMNIwwkDSINIw0NIyMODqAOIiQMIw0jDCQNDSIOIiMNDiIjDCMNDiIjDSMMJAwjDSMMIw4iDQ0jDSIkDSINDSIOIw0jDSIjDSQMIwwjDSQODaENIyMMJA0jDCMNDiMNIiMNDiIkDCMNDiIkDCMNIw0jDCMNJA0iDQ0jDSQiDQ0jDSQiDQ0jDSQjDCMNDSMOIiMODqINIiMNIw0kDCMNDSQNIiMNDSMkDCMNDSMkDCMNIwwkDSMMIw0kDQ0iDSMkDA4iDSMkDA4iDiIkDCMNDSMOIiMPDaENJCMMIw0kDCMNDSMNJCMMDSMkDCQMDSMjDSMNIwwjDiMNIg0jDg0iDiIjDg0jDSIjDg0jDSMjDSMNDSMNIyMPDaINIiQNIwwjDSQMDiINIyQMDiIjDSQMDSMjDCQNIw0iDSQNIg0jDQ0jDiIjDQ0jDiIjDQ0jDiIjDSQMDSMNIyMPDqEOIiQMJAwjDSMMDyINIyMNDiIjDSMNDiIjDSMMJA0jDCMNJA0iDQ0jDSMjDQ0iDiMjDQ0jDSMjDSMMDiMNIyMODqINIiMNIw0jDSMNDSMOIiMMDiMkDCMNDSIkDSMNIwwkDSMMIw0kDQ0iDSMkDA4iDiIkDQ0iDiIkDSMMDiIOIyMABdw=",
    # All-off (turns fan and lamp off in one command)
    "all_off": "scBWAs6eBgAOIiQMIwwkDSMMDSMNIyMMDiIjDSMNDSIjDSQMIw0iDSMOIg0iDgwkIg0iDQ0kIg0jDQ0jIwwjDSIOIwwjDQ0kD6ANIiMNIw0jDCMNDSMOIiMMDSMkDCMMDiIkDCMNIwwkDSMMIw0jDQ0jIwwjDg0jIg0jDg0iIw0iDSQMIw0jDA8kDaENIyMNIw0jDCMNDiIOIiMMDyIjDCQMDSMkDCMMJA0jDCMNIw0jDQ0iIw4iDQ0jIwwkDQ0jIwwkDSINIw0jDQ0kDaEOIiQMIw0jDCQNDSINIyQMDiIjDCQNDSIjDSQMIw0jDCMOIg0jDA0jIw0jDQ0iJAwjDQ0iJA0jDCMMJA0jDQ0kDaEOIiQMIwwkDSMMDiINIyMNDSIlDCMMDiIjDiINIwwjDiINIwwjDQ4jIg0jDQwkIw0iDQ0kIwwjDSMNIwwjDQ0lDqAOIiMMJQwjDCMMDiMOIiMMDiMjDCMNDSMjDSMMIwwkDSMMIw0kDA0jIwwkDQ0iIw0kDQ0iIwwjDiMMIw0jDQ0lDaAOIiQNIwwjDSQMDSMNIyMNDiIjDCMNDiIjDSMMJA0jDCMNIw0jDQ0iJA0iDQ0jIw0jDQ0iIw4iDSMNIg0kDA0lDaENIyQMIwwjDiMMDSMNJCMMDSMjDCQNDSIjDSQMIw0jDCQNIwwjDQ0jIw0jDA0kIwwjDQ0kIwwjDSINJAwjDQ0kD6AOIiMMIw4jDCMNDSIPIiMMDiIkDSMMDSMkDCMNIg0kDSINIwwkDQ0jIg0jDg0iIw0iDQ4jIwwjDSMNIw0iDQ0ABdw=",
    # Fan speeds 1-6
    "fan_1": "scDaAtieBgAOIiQLJAwjDCQNDSIOIiQMDSMjDCMODSIjDSMMJA0iDSINJA0iEQshDCMkDSINIg0kDR4RIg0jDgwjDSMNIg4lDaAOIiMMJA0jDCMMDiMNIiQMDSMkDCMMDiIkDCMNIwwkDSINIwwjDg0iDSMjDCQNIg0jDCQNIg0jDA0jDiIOIg0kDqAOIyMMIwwkDSMMDSIOIyMNDSIjDCQNDSIjDSMNIwwjDSIOIwwjDQ0iDiMjDCMNIw0jDCMNIw4iDQ0iDSMNIw4jDqAOIiQMJAwjDCMNDiINIiMNDiIjDSMMDSQjDCMNIw0jDCMNIwwkDQwjDSIkDSMMIwwjDiINIw0iDQ0jDiINIg4lDaAOIiMMJA0iDSMMDSMOIiMMDiIkDCMNDSIjDiMMIwwjDSMNIwwjDQ0jDSIjDSMNIw0iDSINJA0iDQ0jDCQNIw0kDaENIyMMJAwjDSMMDiINIyQMDSIkDCQMDSMjDCMMJA0jDCMNIw0jDA0jDSMjDSINIwwkDSMMIw0jDQ0iDiINJA0kDaENIiMNIw0jDCMMDiMNIiQMDSMjDSINDSMjDSMMIw0jDSMMIw0iDg0jDCMjDCQMIw0jDCQNIg0iDQ0kDSIOIg0kDqENIiQMIwwkDSMMDSIOIyMMDiIjDSMMDiIjDCQNIwwjDSMNIg0jDQ0iDiIkDCMMJA0iDSMMIw4iDQ0jDCMOIw0kDaAOIiQMIwwkDCQMDiINIyIODSIjDSMMDSMkDCMMJA0iDSMMIw0jDQ0jDSIkDSINIwwjDiINIwwjDQ0jDSMNIg4lDaENIiMMJA0jDCMMDiMNIiMNDSIkDSMMDSIkDSINIwwjDiINIw0iDQ0kDSIjDCQNIg0jDSINIw0jDQ0iDSMOIg0kDqANIyMNIwwjDSMNDSIOIiQMDSIkDCQMDSMjDCMNIw0jDCMNIw0iDQ0jDSMjDCMNIwwkDSINIg0kDQ0iDSMNIw4ABdw=",
    "fan_2": "scBWAtieBgAOISQMIwwkDSMMDSIOIyMMDiIjDSMNDSIjDSQMIw0iDSMNIw0iDQ0kDCMjDSINIw4MIyINDSQiDSMNDCQjDQwlDaENIyMMJAwjDSMNDSIOIiQMDSMjDCQNDSIjDCQNIwwjDSMNIwwjDQ0iDiMjDCMNIw0NIyMMDSQiDSMMDSMkDA4kDaENIiQNIwwjDCQNDSIOIiQMDiIjDCMODSIjDSMMJA0iDSMMJA0iDQ0jDSMjDSMMIwwPIiMMDiIkDCMNDSIkDQ0kDqAOIiQMIw0jDCMODSINIiQMDiIkDCMMDSQjDCMMIw4jDCMNIg0jDgwjDSIkDSMMIw0NIyMNDSIjDSMNDSIjDQ4kDqANIiQMJAwjDSMMDSQNIiMMDiMjDCMNDSIkDSMMIw0jDSMMIw0jDQ0iDiIjDSMNIg0NIyQMDSIjDSQMDSMiDQ0lDqAOIiMMJQwjDCMMDiMOIiMMDiIkDCMMDiIkDCMNIw0iDiMMIw0iDQ4jDSIjDSQMIw0NIiMNDiIjDCMNDiIjDQ0kDaINIiMMJAwkDCMNDSIOIyMMDiIjDSMNDSIjDSQMIwwjDSQMIw0iDgwkDSIjDSIOIw0NIiMNDSMjDSMMDSQjDA0lDaAOIyMMIw0jDSMNDSIOIiQMDiIjDCQNDSIjDCUMIwwjDSMOIg0iDQ0jDiIjDSINJA0MIyMMDiMjDCMNDSIkDQ0kDqAOIiQMIwwkDCQMDiINIyQMDSIkDCMNDiIjDCMNJAwjDSINJA0iDQ0iDSQjDCMMIw0OIiMNDSIkDSMMDSMkDA0ABdw=",
    "fan_3": "scBWAoieBgAOISULJAwjDCQNDSIOIiMMDyIjDCMNDSMjDSMMJA0iDSIOIg4iDgwjDSIkDSINDSMjDQ0jIg0jDgwjIw0MIyQODqAOISQMJAwjDSMMDiMNIiMNDSMjDSMMDiMjDCMNIwwkDCMNIg0kDA4iDSIjDiMMDiIjDA4jIwwjDA4jIwwOIiQODqANIiMNJAwjDCQMDSMOIiMMDiIkDCMNDSIkDSINIwwjDSMNIwwjDQ4iDSMjDCQMDiIjDA4jIwwjDQ0jIwwOIiMOD6ANIyMMIw0jDSMMDSMNIyMNDSIjDiMMDSIjDSQMIw0jDCQMIw0iDQ0jDiIjDCMODSIjDQ0iJAwjDQ0iJA0NIiMPDaAOIyMMIwwkDSMMDiINIiQNDSIjDCUMDSIkDCQMIw0jDCMNIw0iDQ0iDyIjDCMNDSMjDA4iIw0jDQ0iIw0OIiMODqANIyQMIwwjDSQMDiINIyQMDiIjDCMODSIjDCMNJAwjDSINJAwjDQ0iDiMjDCMNDSMkDA0jIwwkDQ0iIwwOIyMODqAOIiQMIwwkDCMNDiINIiMNDiIjDSMMDSQjDCMMJA0iDSMNIg0kDQwjDSMkDCMNDSIkDA4iIwwjDg0iIw0NIiQODqAOIiMMJA0jDCMMDiMNIiQMDSMkDCMMDiMjDCMNIwwkDSINIwwkDQ0iDSMjDSMNDSIjDQ4iIw0jDA0kIwwNIiUODaENIiMNJAwjDCMNDSQNIiMNDSIkDSMMDSMkDCMMIw0jDSMNIwwjDQ4iDSIkDCQMDiIjDA4jIwwjDQ0jIw0NIiMABdw=",
    "fan_4": "scBWArqeBgAOIiQLJAwkDCMNDSINJCMMDSMjDSMNDSIjDSQMIw0iDSMOIg0iDgwjDSMjDSINDSQNIg4iDSMjDSMMIw0kDCMPDaAOIiQMIw0jDCQNDSIOIiMNDiIjDCMNDiIjDSMMJAwjDSMMIw4iDQ0jDSIkDSINDSIOIw0jDSIjDSQMIwwjDSQODaENIiMNJAwjDSMMDSQNIiMNDSIkDSMMDSIkDSMMIw0jDSMNIg0iDQ4jDSIjDSQMDiINIg4jDSMjDCMMJA0jDCMPDaAOIyMNIg0kDCMNDSIOIiQMDiIjDCQNDSMjDCMNIw0iDSMMJA0jDA0jDSMjDSMMDSQNIg4iDSMkDCMMIw0kDCMPDaANIyQMIw0jDCMODSIOIiMMDiMjDCMNDSMjDSMMIw0jDSMNIg0jDQ0jDSIjDSMNDSMNIg4jDSIjDSQMIwwjDSMPDaENIiMNIw0jDCMNDSIPIiMMDiIkDCMNDSIjDiMMIwwjDSQMIw0iDQ0kDSIjDSMMDiMNIg4iDSMjDSMMIw4iDSMODaENJCMMIwwjDCQNDSIOIiQMDiIjDCMNDiIjDCMNIw0jDCMNIw0jDQwjDSIkDSINDSMNIw4iDSIkDSMMIwwjDSQODaENIiMNJAwjDCMNDSMOIiMMDiMjDCMNDSIkDCMNIwwkDSINIw0iDg0iDiIjDCQNDSINIw0jDiIjDCMNJAwjDCMPDaEOIiMMIw0kDCMMDiINJCMMDSMjDCQMDiIjDCQNIg0jDCMOIw0iDQ0jDSMiDSMMDiMNIg4iDSQjDCMMIw0kDCMABdw=",
    "fan_5": "scBWAs6eBgAOISULJAwjDSMNDiINIiMNDiIjDSMMDSQjDCMNIg4jDSINIw0jDQ0jDCMkDQ0iIw0iDSMNIw0iDQ0kDSIjDA4lDaENIiMNIw0jDSMMDiIOIiQMDSMkDCMNDSIjDiMMIw0iDSQMIw0jDA0kDSMiDQ0kIwwjDSINJAwjDQ0jDSMjDQ0kDqAOIyMMIw0jDCQNDSIOIiQMDiIjDCMODSIjDSMMJA0jDCMNIw0jDA4iDSQiDQ0jIwwkDCMNIwwkDQ0iDiIjDQ4kDaENIiMOIwwjDSMMDSQNIiMNDSQiDSMNDSMjDSMMIw0jDSMMIw0jDQ0jDSIjDQ4iIw0iDSQMIw0jDA0kDSIjDQ0kD6ANIiQMIwwkDSMMDSMNIyQMDSMjDSMMDiIjDCQNIwwjDSMNIw0iDQ0jDSMjDA0jJAwjDSMMJA0iDQ0jDSIkDQ0kDqANIyQMIw0jDCQMDiINIyMNDSMjDCMMDyIjDCMNJAwjDSINIw0jDQ0iDiIkDA4iIw0jDSMMIw0iDg0jDSIjDQ0lDaENIyMMJAwjDCMNDSMOIiMMDiIkDCMNDSIkDSMMIw0iDiMMIw0iDQ4jDSIjDQ0jIw0jDCMNIw0jDA0jDiIjDA4kDqAOIyMMIwwkDSMMDSMNIyMNDSIkDCQMDiIjDCQNIwwjDSINJA0iDQ0jDSMjDQ0iIw4jDCMNIg0kDA4iDSMjDQ0lDaAOIiQMIw0jDCMODSIOIiMMDyIjDCQMDSQjDCMMIw4jDCMNIg0kDQ0iDSMkDA0jIwwjDSMNIw0iDQ0kDSIjDQ0ABdw=",
    "fan_6": "scBWArqeBgAOISULJAwjDCUMDSIOIiQMDiIjDSIODSMiDSMMJA0jDCMNIw0iDgwjDSQiDQ0iIw0OIiMNDSIkDCMNIwwNJA0kDqANIyQMIwwjDSMNDiINIiMNDiIkDCMMDiMjDSMMJAwjDSMNIg0kDA0jDSIkDQ0iIw0NIyMNDSIjDiMMIw0NIg8kDaENIiQMJAwjDCQMDSQNIiQMDSMjDSMMDSMkDCMMIw0kDCMNIwwkDQwjDSMjDQ0jIwwOIiQMDiIjDCQNIwwOIg0lDqAOIiMMJA0jDCMNDSMNIyMMDiIkDCMNDSIkDSMMIw0jDSMMIw0jDA4jDSIjDQ0jIw0NIiQNDSIkDCMNIw0NIg4kDqENIiQMIwwkDSMMDSMNIyMNDSIkDSINDSMjDSMNIg0jDSMNIwwjDQ0jDSMjDA4jIwwOIiMMDyIjDCMNJAwNIw0kDqENIyMNIwwkDCMNDSIOIyMNDSIkDCQMDSMjDCQNIg0jDSIOIwwjDQ0iDyIjDQ0iJA0NIiMNDSMkDCMMIw4NIg4kDqANJCMMIwwkDCQMDiINIyQMDiIjDCQNDSIjDCMOIwwjDSMMJA0iDQ0jDSMjDQ0iIw4NIiMNDSIkDSMMIw0NIw0lDaAOIiQMJAwjDCQNDSIOIiMNDiIjDCMNDiIkDCMMJA0jDCMNIg4jDQwjDSMkDA0jIwwOIyMMDiIkDCMNIwwNJA0kDqAOIiMNIwwkDCMMDyIOIiMMDiMjDCQMDSQjDCMNIg4jDSINIwwkDQ0jDSIkDQ0iIw0NIyMMDiIjDSMNIwwOIg0ABdw=",
    # Fan-only off (light stays on)
    "fan_off": "scBgAbqeBgAOIg0mDCINIiUMDiINIw0lDqEOIiMMJQwjDCQMDiMOIiMNDiIjDSMNDiIjDSMMJA0jDSINJA0iDQ0jJAwjDSMNDSMNIw0jDSQNIiMNDSQNIg4kDqINIyMMJA0jDCQMDSQNIiQMDSQjDCMNDSQjDCMNIw0jDSMMIw4jDQ0iIw4jDSINDSMOIg4iDiIPIiMNDSIPIg4kDaEOIyQMIwwlDCMMDiIOIyMNDSIlDCMNDSIlDCMNIwwkDSMNIg0kDQ0iIw0kDCMNDSMNIw4iDiINJCMMDiIOIw0lDaEOIiQMJAwjDSQMDiIOIiQMDiIkDCQMDiIjDSQMJAwjDSQMIw0jDA0kIw0jDCQNDSMNIg4jDiINIyQMDiIOIg4lDaEOIiMOIwwkDCMNDiIOIiMMDyIjDSMMDyIjDSMMJA0jDSINJA0iDQ0jJA0iDSMNDiMNIg4iDyINIyMMDyIOIg0ABdw=",
    # Step buttons (act on whichever is active)
    "brightness_up": "scBWAqaeBgAOISYLJAskDCQMDiINIiUMDSMjDCQNDSIjDSMNIw0jDCMOIg0iDgwkIg0NIyMMJA0jDCMNIw0NIyMMJA0NIiMPDaEOIiMNIg4jDCMNDSIPIiMMDiIkDSMMDSMkDCMMIw0kDCMNIg0kDQ0iIw0NIyMNIwwkDSINIw0NIyMMIw0NIyMODqANIyQMIw0jDCQNDSINIyQMDSMjDCQMDiIjDCMOIg0jDSIOIwwjDQ0iJA0NIiMNJAwjDSMMJA0NIiMNJAwNIyMODqENIyMMIw4jDCMNDSIOIyMMDiIkDCMNDSIkDSMMIw0kDCMNIg0kDQwjIwwOIyMNIg0kDSINIw0NIyMMIw0NJCMODaENIiUMIwwjDSQMDSMNIyMNDSMjDCMNDiIjDSMOIg0jDCMOIwwjDQ0iJA0NIyMMJA0iDSMNIw0NIyMMJA0MIyMPDaINIiMNIw0jDSMMDSMOIiQMDSMkDCMNDSIkDSMMIw0jDSMMIw0kDA0jIwwNJCMMIw0kDCMNIwwOIyMMIw0NJCIPDaENIyQMIw0iDSQNDSINIyQMDiIjDCQNDSIjDSMNIw0jDCMOIwwjDQ0iJA0NIyMMJA0iDSMNIw0NIiMNJAwNIyMODqEOIiMMJA0jDCMNDSMOIiMNDSIkDSMMDiIkDSMMIw0jDSMNIg0kDA0jIwwOIyMMIw0kDSINIwwNJCMNIg0NJCMODaEOIiQMIwwjDSQMDiINIyQMDiIjDCQNDSIjDSMNIw0jDCMOIg0jDQ0iJA0NIiMNJAwjDSINJA0NIiMMJA0NIiMABdw=",
    "brightness_down": "scDkANieBgAjDCMNDiMNIiMNJA0NIiMNJA0iDQ0jJA8Mog0iJA0jDSMNIw0OIg0jIw0OIiMNIwwPIiMNIw0jDSMNIg0kDSMMDSMkDSINDSMNJCMNIg0NJCMMIw0kDQ0iIw8NoQ8iIw0jDCQNIwwOIg4jIwwOIiUMIw0NIiQNIwwjDSQNIwwjDSQMDSMjDSMNDSMNIyMOIwwNIyMNIw0jDQ0iJA8NoQ4iJA0jDCMNJAwOIg4iIw4NIiQMIw4NIiQMIw4jDCMNIwwkDSMNDSIkDSMMDiIOIyMNIwwOIyMNIwwkDQ0iIwAF3A==",
    # Special preset
    "natural_wind": "scCYAtieBgAPISQLJgskDCMMDiMNIiQMDSQjDCMNDSQjDCMNIwwkDSINIg4jDQ0jIg0kDSINDSMkDA0jIw0jDSMNIg0NJCMODaEOIiQMIw0jDSQMDSMNIiQNDSMjDCQNDSMiDSQNIwwjDSQMIw0iDQ0kIw0iDSMODSIjDQ0kIg0jDSIOIw0NIiMPDqENIyINJA0iDSMNDSMNIyMNDSMjDSMMDSQjDCMNIw4iDSMNIg0jDgwjIw0jDSMNDSMkDA0jIw0jDSMMIw0NJCMODqENJCINIw0iDSQNDSMMIyQNDSIjDSQNDCMjDSQNIg0jDSMNIw0iDQ0kIwwjDSMNDSMjDQ0jIw0iDSMOIg4MIyMQDKINIyINJA0iDSMMDiMNIyMNDCQjDSINDSQjDSINIw4iDSMNIg4jDQ0iIw0kDSINDSMjDQ0jIg4jDSIOIg0MJSIPDaENJCMMIw0jDSMNDSMNIyMNDSMjDSMNDSMiDSQNIg0jDSMNIw0iDgwkIw0iDSQNDSMiDQ0kIg0jDSIPIg0NIyIQDaIMIyMNIw4iDSIODCQNIyMNDCQjDSINDSQiDSMNIw4iDSIOIg4jDQwjIw4iDSMNDSMjDQ0jIg4jDSIOIg0PIiIPDaENJCMNIg0jDiINDSMNJCINDSMjDSMNDSMiDiMNIw0iDSQNIg0jDQ0jIw0iDSQNDSIjDQ0kIg4iDSMOIg0NIyIQDaINIiMNJAwjDSMMDiMNIyMNDSMjDSMNDCQjDSMMJA0jDSINIg8iDQ0jIg8iDSIODCQjDQ0jIg0kDSINIw0OIiMPDaENJCMMIw0kDCMNDSIOIyMNDSMiDiMNDSIjDSMNIwwjDSQNIg4iDQ4jIg0jDSMNDSMiDgwkIg4iDSMNIw0NIyMABdw=",
    # Fan reverse direction toggle
    "fan_direction": "scBWAuyeBgANIiQLJQwkDCMNDSINJCMMDSMjDSMNDSIjDSQMIw0iDSMOIg0iDgwjDSQjDQwjDSMjDQ0jDSIlDCMMDiIOIyMODqAOIyMMJAwkDSMMDiINJCMMDiIkDCMNDSMkDCMNIwwkDSMMIw0jDQ0jDSIjDg0jDSIjDg0jDSIjDiMMDiIOIyMODqAOIiQNIwwjDSQMDiINIyQMDiIjDCQNDSIjDSQMIw0jDSMNIw0iDQ0kDSIkDA0kDSMjDA4jDSMjDCQNDSMNIiUODaENIyMMJA0jDCMNDiMNIiMNDiIkDCMNDiIkDCMNIw0jDCMNJA0iDQ0jDSQiDQ0jDSQiDQ0jDSQjDCMNDSMOIiMODqINIiMNIw0kDCMNDSQNIiMNDSMkDCMNDSMkDCMNIwwkDSMMIw0kDQ0iDSMkDA4iDSMkDA4iDiIkDCMNDSMOIiMPDaENJCMMIw0kDCMNDSMNJCMMDSMkDCQMDSMjDSMNIwwjDiMNIg0jDg0iDiIjDg0jDSIjDg0jDSMjDSMNDSMNIyMPDaINIiQNIwwjDSQMDiINIyQMDiIjDSQMDSMjDCQNIw0iDSQNIg0jDQ0jDiIjDQ0jDiIjDQ0jDiIjDSQMDSMNIyMPDqENIiQMJAwjDSMMDyINIyMNDiIjDSMNDiIjDSMMJA0jDCMNJA0iDQ0jDSMjDQ0iDiMjDQ0jDSMjDSMMDiMNIyMODqINIiMNIw0jDSMNDSMOIiMMDiMkDCMNDSIkDSMNIwwkDSMMIw0kDQ0iDSMkDA4iDiIkDQ0iDiIkDSMMDiIOIyMABdw=",
}
